version: '3.0'

admin-environment: &admin-environment
  - ...

backend-environment: &backend-environment
  - ...

services:
  backend:
    container_name: backend
    build:
      context: . 
      dockerfile: ./backend.Dockerfile
    environment: *backend-environment

  elastic:
    container_name: elastic
    build:
      context: 'git repository address'
    ports:
      -$ELASTIC_PORT:$ELASTIC_PORT
    environment:
      - TZ=Moscow/Europe
    volumes:
      -elastic:/usr/share/elasticsearch/data

  postgres:
    container_name: postgres
    image: postgres:13
    expose:
      - $POSTGRES_PORT
    environment:
      - POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      - POSTGRES_USER: $POSTGRES_USER
      - POSTGRES_DB: $POSTGRES_DB
      - TZ=Moscow/Europe
    volumes:
      -postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    expose:
      - $REDIS_PORT
    environment:
      - TZ=Moscow/Europe
    volumes:
      -redis:/data

  admin_panel:
    container_name: admin_panel
    build:
      context: 'git repository address'
    environment: *admin-environment
  
  nginx:
    container_name: nginx
    build: 
      context: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volumes:/code/staticfiles    

volumes:
  -redis
  -elastic
  -static_volumes
